kotlin.code.style=official

# Done to increase the memory available to gradle.
# Also disable unsafe memory access warnings, caused by ktlint. See https://github.com/JLLeitschuh/ktlint-gradle/issues/944
org.gradle.jvmargs=-Xmx2G --sun-misc-unsafe-memory-access=allow
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

# Minecraft
mcVersion=26.2

# Paper
paperVersion=26.2.build.+
paperApiVersion=26.2
