package net.voxelpi.varp.environment

import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.supervisorScope
import net.voxelpi.varp.compositor.Compositor
import net.voxelpi.varp.compositor.CompositorMount
import net.voxelpi.varp.environment.EnvironmentDefinition.Builder
import net.voxelpi.varp.repository.Repository
import net.voxelpi.varp.tree.Tree
import org.slf4j.Logger
import org.slf4j.LoggerFactory

public class VarpEnvironment internal constructor() {

    private val logger: Logger = LoggerFactory.getLogger(VarpEnvironment::class.java)

    /**
     * The currently loaded repositories.
     */
    public val repositories: Map<String, Repository<*, *>>
        field = mutableMapOf<String, Repository<*, *>>()

    /**
     * The compositor that is generated by the loader.
     */
    public val compositor: Compositor = Compositor(emptyList())

    /**
     * The tree of the compositor.
     */
    public val tree: Tree
        get() = compositor

    public fun registerRepository(repository: Repository<*, *>) {
        repositories[repository.id] = repository
    }

    public fun unregisterRepository(id: String): Repository<*, *>? {
        return repositories.remove(id)
    }

    public suspend fun load(definition: EnvironmentDefinition): Result<Unit> = runCatching {
        // Clear the compositor.
        compositor.clear()

        // Close all previously loaded repositories.
        supervisorScope {
            repositories.values
                .map { async { it.close() } }
                .awaitAll()
                .forEach { it.getOrThrow() }
        }
        repositories.clear()

        // Load new repositories.
        repositories.putAll(definition.repositories.mapValues { (id, def) -> Repository(id, def.storage, def.defaultState) })

        // Open all currently loaded repositories.
        supervisorScope {
            for (repository in repositories.values) {
                launch {
                    repository.open().onFailure {
                        logger.error("Could not open repository '${repository.id}': ${it.message}", it)
                    }
                }
            }
        }

        // Update compositor mounts.
        val mounts = mutableListOf<CompositorMount>()
        for ((targetPath, mountDef) in definition.mounts) {
            val repository = repositories[mountDef.repository] ?: run {
                logger.error("Unable to create mount '$targetPath', unknown repository '${mountDef.repository}'")
                continue
            }
            if (!repository.storage.isOpen) {
                logger.error("Unable to create mount '$targetPath', repository '${mountDef.repository}' failed to open")
                continue
            }
            mounts += CompositorMount(targetPath, repository, mountDef.sourcePath, mountDef.state)
        }
        compositor.modifyMounts(mounts).getOrThrow()
    }

    /**
     * Deactivates the compositor and all loaded repositories.
     */
    public suspend fun close(): Result<Unit> = runCatching {
        // Deactivate the compositor.
        compositor.clear()

        // Deactivate all existing repositories.
        coroutineScope {
            for (repository in repositories.values) {
                launch {
                    repository.close().getOrThrow()
                }
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    public fun save(): EnvironmentDefinition {
        return EnvironmentDefinition(
            repositories.mapValues { RepositoryDefinition.repositoryDefinition(it.value) },
            compositor.mounts().associate { it.targetPath to MountDefinition(it.repository.id, it.sourcePath, it.state) },
        )
    }

    public companion object {

        public fun empty(): VarpEnvironment {
            return VarpEnvironment()
        }

        public suspend fun environment(definition: EnvironmentDefinition): Result<VarpEnvironment> {
            val environment = VarpEnvironment()
            environment.load(definition)
            return Result.success(environment)
        }

        public suspend fun build(builder: EnvironmentDefinition.Builder.() -> Unit): Result<VarpEnvironment> = runCatching {
            val definition = EnvironmentDefinition.environmentDefinition(builder)
            val environment = VarpEnvironment()
            environment.load(definition).getOrThrow()
            return@runCatching environment
        }
    }
}
